### ISSUE TITLE
Wrapping Text

### ISSUE THREAD

**Issue by hansl** [Finomnis/u8g2-fonts#16]
Is there a way to wrap text based on the Font? With a Monospace font this is relatively easy.

Basically either allow wrapped rendering with a bounding box, or calculate where the break points would be so an application can insert new lines. WDYT?

**Comment by Finomnis** [comment]
I'm not entirely sure if I understand, would you mind giving me an example?

**Comment by Finomnis** [comment]
Theoretically, [`embedded-text`](https://crates.io/crates/embedded-text) should be compatible with the CharacterStyle API of this crate. This should give you exactly what you are asking for.

Although I have to warn you, I didn't actually test this yet. But if you give it a go, I'd be interested in your experience and would be willed to answer questions.

**Comment by hansl** [comment]
So I've got some text, and I want to wrap it to fit horizontally. What I'd like, I guess, is to have a version of `get_rendered_dimensions` (and `render`) that has a maximum width.

**Comment by hansl** [comment]
Thanks, I'll try it and report back here.

**Comment by hansl** [comment]
It seems to work great with `embedded-text`, thanks!

**Comment by Finomnis** [comment]
Very happy to hear that! In case you don't mind, I'd love to see a picture! 
If that's too much effort, though, also fine :)

**Comment by hansl** [comment]
Sure. So I have a special renderer and not using TextBox (yet) to do the bottom bar here:

![IMG_2613](https://github.com/Finomnis/u8g2-fonts/assets/681969/fb531576-a17f-4167-8bc4-89f595fb21ed)

The reason I cannot use TextBox is that I haven't (yet) found a way to tell it "only size this box as much as you need". TextBox takes a bounds and can only stretch vertically AFAIK (I'm looking into it but I have more pressing issues to figure out).

And use TextBox here since that takes a LOT of space:

![IMG_2614](https://github.com/Finomnis/u8g2-fonts/assets/681969/862598cb-119e-4595-a244-a29e654a363d)

**Comment by Finomnis** [comment]
Well, glad to see this crate used :) The `embedded-graphics` community is quite small so far, so I'm happy to see some action :)
