### ISSUE TITLE
Add support for custom character mappings

### ISSUE THREAD

**Issue by robertbastian** [Finomnis/u8g2-fonts#21]
My understanding is that the u8g2 font format supports up to 256 glyphs, with pretty much custom encodings (whatever is in the BDF). If I want fancy unicode characters, it's possible with a custom BDF, the limitation is just that I can have at most 256 glyphs. Now, if I use a custom mapping in the encoded font, it'd be nice to tell the renderer about it. Otherwise I have to reencode all my strings at runtime, or work entirely in the custom encoding, which is very painful.

**Comment by Finomnis** [comment]
I'm not entirely sure what you mean. Where did you get this information from? What are you referencing here?

This crate does not use bdf files directly. It uses the C source code of the U8g2 fonts.

**Comment by robertbastian** [comment]
The u8g2 repo contains a tool to convert BDF files into the custom byte representation, which can then be used by this crate.

BDF files can use arbitrary byte encoding, there are some predefined ones in [`otf2bdf`](https://github.com/olikraus/u8g2/tree/master/tools/font/otf2bdf/maps), but one can also use a custom one. For example I could use the ASCII bell (0x07) code point for useful non-ASCII character's bitmap. However, then I have to use `\u0007` in my code everywhere to refer to this character, instead of using its actual code point. It would be nice to tell the library that I've done this so it takes it into account when looking up the glyph for a `char`.

I think this is a particular issue for Rust, as in C the client is usually left to fend for themselves when it comes to encodings, but in Rust everything is assumed to be Unicode and UTF-8 (which is great!).

Now that I'm actually looking at the [code](https://github.com/Finomnis/u8g2-fonts/blob/main/src/font_reader/mod.rs#L93), there seems to be some support for BMP characters, so maybe there's already a way to do this. Anyway, with a custom mapping one could encode non-BMP characters as well.

**Comment by Finomnis** [comment]
All fonts in this crate are encoded using https://github.com/olikraus/u8g2/wiki/u8g2fontformat. This crate does not have bitmap support.

You can of course create your own fonts if you have the binary data that is encoded in the specified way. You need to then create an empty struct and [`impl Font`](https://github.com/Finomnis/u8g2-fonts/blob/main/src/fonts.rs) for it. It should then simply work with this library.

Im not sure what you mean with this custom mapping. The font format already supports full unicode, use specify the desired character directly. No need to map to `0x0007` or similar.

**Comment by Finomnis** [comment]
> My understanding is that the u8g2 font format supports up to 256 glyphs

I think this is your mistake. This is wrong, the U8g2 don't format supports 16 bit unicode.

Like for example these fonts:
https://github.com/olikraus/u8g2/wiki/fnticons

**Comment by Finomnis** [comment]
@robertbastian Any feedback? Can I close this?

**Comment by robertbastian** [comment]
I guess, I have a workaround.
