### ISSUE TITLE
Use generate font file scripts from crate

### ISSUE THREAD

**Issue by Rico1502** [Finomnis/u8g2-fonts#8]
Is it possible to move the generate font file tool, such that it is usable from another rust project in order to automate the process of converting true type fonts (or anything convertible to bdf format) to this Rust representation?

I make this request, as I were using the tool locally on my PC, but do not want to commit it into an Git project which is licensed completely different and the tool does not have any licensing information.

**Comment by Finomnis** [comment]
Should theoretically be possible :)
Not sure if I'll get to publish it any time soon, though, I'm quite busy at the moment

**Comment by Finomnis** [comment]
It can only handle pixel based fonts, though... It can't deal with true type directly.

**Comment by Rico1502** [comment]
> It can only handle pixel based fonts, though... It can't deal with true type directly, or alpha. It can only deal with binary fonts

I have programs (otf2bdf and then bdfconv) to handle that problem though.

**Comment by Finomnis** [comment]
I'm afraid that I have to tell you that I don't even generate them out of BDF files. I directly copy the binary representation from [`u8g2_fonts.c`](https://github.com/olikraus/u8g2/blob/7e58b87b3cd63ed4016624cd00226ffe4f0bfe1d/csrc/u8g2_fonts.c), as seen in [this script](https://github.com/Finomnis/u8g2-fonts/blob/66dbea1384ddddec951842e08b36d66e8158869c/regenerate_fonts_file.sh), which executes [this program](https://github.com/Finomnis/u8g2-fonts/tree/main/tools/generate_fonts_file).

But the conversion from BDF to U8g2 internal encoding is done by U8g2 to my knowledge; I'm uncertain how this is done though.

**Comment by Finomnis** [comment]
@Rico1502 Does this close this issue, or can I do something else for you?

**Comment by Rico1502** [comment]
Yes. That is fine. Then we'll have to find another way to get ttf fonts on our devices. But thank you anyways!

**Comment by Finomnis** [comment]
Sorry I couldn't help... I know U8g2 does at some point use BDF in its pipeline, maybe you can find the scripts they use to generate their files, then you can just my crate to render them. Feel free to open another issue if you require further assistance from me.

**Comment by ria8651** [comment]
I made a bdf2u8g2 tool so I could use CJK fonts with this crate [here](https://github.com/ria8651/bdf2u8g2). Would be nice to have a more polished version that can generate fonts at compile time as part of this crate.

**Comment by Finomnis** [comment]
You should theoretically be able to impeller the font trait in external crates as well, so I think the better solution would be to create a second create that provides the font and uses my crate for rendering.

**Comment by Finomnis** [comment]
If you need any help or have specific questions, feel free to ask, though.

**Comment by ria8651** [comment]
> You should theoretically be able to implement the font trait in external crates as well

Yea that's what I did and it worked fine.

> @ria8651 If you need any help or have specific questions, feel free to ask, though.

I was wondering why the Font trait was implemented the way it was? Having it be a static attached to the trait makes unit tests difficult. It would make more sense for me to have the trait contain a function that returns a static reference to the data. I also don't see why the data needs to be static and not be attached to a lifetime besides code readability. Though its not too annoying to just use files and I cant think of any use cases besides tests. Maybe for uploading fonts to the device at runtime or something.

Also thanks for making this crate, its quite nice having a way to use compressed fonts with embedded-graphics

**Comment by Finomnis** [comment]
> I was wondering why the Font trait was implemented the way it was? Having it be a static attached to the trait makes unit tests difficult. It would make more sense for me to have the trait contain a function that returns a static reference to the data. I also don't see why the data needs to be static and not be attached to a lifetime besides code readability. Though its not too annoying to just use files and I cant think of any use cases besides tests. Maybe for uploading fonts to the device at runtime or something.

The main reason is optimization. All of the fonts combined are roughly 9MB, which you definitely do not want inside of your microcontroller. So using zero sized types together with static references makes it super easy for the compiler to optimize away unused fonts and doing compile time optimization.

Having a function that returns a reference would create some runtime overhead and would make it less reliable that the unused fonts really do get removed. That's pretty much all there is to it :)
